### ISSUE TITLE
Script to install additional VVV dependencies

### ISSUE THREAD

**Issue by davetgreen** [mkdo/kapow-skeleton#13]
Investigate a shell script to go into the Skeleton that adds Bower, PHPdocumentor and any other software dependencies for those wanting to rely on Vagrant and not their local set-up. 

This would probably run on provision, so after the first site has been provisioned with Kapow, that VVV install would come complete with this extra software. If not, I guess it's something to run on an ad-hoc basis.

**Comment by davetgreen** [comment]
@mwtsn may not actually need much/any proper "scripting for this", we just need a utilities repo that VVV uses upon provision, and update the config like so...

Just had a DM chat on Slack with Lorelei and we can do it this way in the config:

```
utility-repos:
  unofficial: https://github.com/LoreleiAurora/vvv-utilities-2.git
  unofficial2: https://github.com/LoreleiAurora/vvv-utilities-3.git

// Defining utilities to install
utilities:
  official:
  // Utilities in the official repository
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind
  unofficial:
  // Utilities in the unofficial repository defined above
    - test1
    - test2
    - test3
  unofficial2:
  // Utilities in the unofficial2 repository defined above
    - test4
    - test5
    - test6
```

Also, were free to PR the VVV utilities repo and add what we need to that list, she's happy to support extra utilities if we can justify why. Bower and PHPdocumentator should be pretty easy to justify.
